spring:
  application:
    name: web-service
  config:
    import: "optional:configserver:"
    discovery:
      enabled: true
      serviceId: config-service
server:
  port: ${APP_PORT:8082}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}