version: "3.9"

services:
  discovery-server:
    build: ./service-discovery
    ports:
      - 8761:8761
      - 8083:8080
    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8083/eureka/"
      EUREKA_URI: "http://discovery-server:8761/eureka"
      APP_PORT: 8761

  age:
    build: ./age-service
    links:
      - discovery-server
    depends_on:
      - discovery-server
    ports:
      - 8081:8080
    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8083/eureka/"
      EUREKA_URI: "http://discovery-server:8761/eureka"
      APP_PORT: 8080

  greeting:
    build: ./greeting-service
    links:
      - discovery-server
    depends_on:
      - discovery-server
    ports:
      - 8082:8080
    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8083/eureka/"
      EUREKA_URI: "http://discovery-server:8761/eureka"
      APP_PORT: 8080

  web:
    build: ./web-service
    links:
      - discovery-server
    depends_on:
      - discovery-server
    ports:
      - 8084:8080
    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8083/eureka/"
      EUREKA_URI: "http://discovery-server:8761/eureka"
      APP_PORT: 8080