spring:
  application:
    name: age-service
server:
  port: ${APP_PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true