spring:
  application:
    name: age-service
  config:
    import: "optional:configserver:"
    discovery:
      enabled: true
      serviceId: config-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true