spring:
  application:
    name: greeting-service
  config:
    import: "optional:configserver:"
    discovery:
      enabled: true
      serviceId: config-service
server:
  port: ${APP_PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true