spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Widliwoo/cloud-learning
          searchPaths: configurations
          clone-on-start: false
          timeout: 8
          skipSslValidation: true
          refreshRate: 0
server:
  port: ${APP_PORT:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true